# Generated by Django 5.0.1 on 2024-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshop_app', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('vendoe_id', models.CharField(max_length=100)),
            ],
        ),
    ]
