# Generated by Django 5.0.1 on 2024-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshop_app', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoomsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'showroomslist',
            },
        ),
    ]
