# Generated by Django 5.0.1 on 2024-02-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshop_app', '0007_showroomslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='ShowRoomsList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showRoomsList', to='gshop_app.showroomslist'),
        ),
    ]
